-- Find total customers by country.
SELECT 
	country, COUNT(*) AS customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY customers DESC

-- Find total customers by gender.
SELECT 
	gender, COUNT(*) AS customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY customers DESC

-- Find total products by categories.
SELECT 
	category, COUNT(*) AS products 
FROM gold.dim_products
GROUP BY category
ORDER BY products DESC

-- What are the average costs in each category?
SELECT 
	category, AVG(CAST(cost AS INT)) AS average_cost 
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	dp.category, SUM(fs.sales_amount) AS total_revenue 
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- Find total revenue generated by each customer.
SELECT
	dc.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key,
		 dc.first_name,
		 dc.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?

SELECT 
	dc.country,
	SUM(fs.quantity) total_quantity
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_quantity DESC
